# Generated by Django 4.2 on 2023-05-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.imagegallery'),
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
