# Generated by Django 4.2 on 2023-05-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegallery',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coreapp.shop'),
            preserve_default=False,
        ),
    ]
