# Generated by Django 4.2 on 2023-05-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_shop_created_at_shop_house_no_shop_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='imagegallery',
            name='user',
        ),
    ]
