# Generated by Django 4.2 on 2023-05-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_image', to='coreapp.imagegallery'),
        ),
    ]
