# Generated by Django 4.2 on 2023-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_alter_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='gallery',
        ),
        migrations.AddField(
            model_name='image',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, related_name='gallery_image', to='coreapp.imagegallery'),
        ),
    ]
