# Generated by Django 4.2 on 2023-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_customuser_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='login_for',
            field=models.CharField(choices=[('shop', 'shop'), ('Account', 'Account')], default='Account', max_length=20),
        ),
    ]
