# Generated by Django 4.2 on 2023-05-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_shop_login_for'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='login_for',
            new_name='login_from',
        ),
    ]
