# Generated by Django 4.2 on 2023-05-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_rename_login_for_shop_login_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='login_from',
        ),
    ]
